services:
    ping:
        build: .
        command: ping faang speedtest --window=3s --elastic=http://localhost:9200/
        #sysctls:
        #    - net.ipv4.ping_group_range=0 2147483647
        network_mode: host
        depends_on:
           elasticsearch:
               condition: service_healthy
        read_only: true
        restart: unless-stopped

    ndt7:
        build: .
        command: ndt7 monitor --period=10m --window=3s --elastic=http://localhost:9200/
        #sysctls:
        #    - net.ipv4.ping_group_range=0 2147483647
        network_mode: host
        depends_on:
            elasticsearch:
                condition: service_healthy
        read_only: true
        restart: unless-stopped

    kibana:
        image: kibana:8.3.3
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        volumes:
            - kibana-data:/usr/share/kibana/data
        depends_on:
            elasticsearch:
                condition: service_healthy
        read_only: true
        restart: unless-stopped

    elasticsearch:
        image: elasticsearch:8.3.3
        ports:
           - "9200:9200"
        environment:
            discovery.type: single-node
            xpack.security.enabled: "false"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        tmpfs:
            - /tmp
            - /usr/share/elasticsearch/logs
        healthcheck:
            test: curl -s http://localhost:9200 >/dev/null || exit 1
            interval: 10s
            timeout: 10s
            retries: 60
        restart: unless-stopped

volumes:
    elasticsearch-data:
        driver: local
    kibana-data:
        driver: local
