services:
    ping:
        build: .
        command: ping -q faang speedtest --window=3s --elastic=http://elasticsearch:9200/
        sysctls:
            - net.ipv4.ping_group_range=0 2147483647
        links:
            - elasticsearch
        restart: unless-stopped

    ndt7:
        build: .
        command: ndt7 monitor --period=1h --window=3s --elastic=http://elasticsearch:9200/
        sysctls:
            - net.ipv4.ping_group_range=0 2147483647
        links:
            - elasticsearch
        restart: unless-stopped

    elasticsearch:
        image: elasticsearch:8.3.3
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: single-node
            xpack.security.enabled: "false"
        restart: unless-stopped

    kibana:
        image: kibana:8.3.3
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        links:
            - elasticsearch
        restart: unless-stopped
